name: Pruebas Biblioteca - CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: biblio
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalación Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Preparación Base de Datos
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS biblioteca;"
          mysql -h 127.0.0.1 -u root -proot biblioteca < biblioteca.sql

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: Ejecución de microservicios
        run: |
          python services/usuarios/app.py &
          python services/paises/app.py &
          python services/autores/app.py &
          python services/editoriales/app.py &
          sleep 3

      # Ejecutar todas las pruebas
      - name: Ejecución pruebas con Pytest
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: biblioteca
        run: |
          pytest services/usuarios/test_usuarios.py
          pytest services/paises/test_paises.py
          pytest services/autores/test_autores.py
          pytest services/editoriales/test_editoriales.py